 /******************************************************************************
 *
 * File Name: Port_PBcfg.h
 *
 * Module: Port
 *
 * Description: Post Build Configuration Header file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Khaled Saleh
 ******************************************************************************/
/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/************************************************************************************/

#include "Port.h"

/* checking the software version compatibility */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of Port_Cfg.h does not match the expected version"
#endif

/* checking the AUTOSAR version compatibility */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of Port_Cfg.h does not match the expected version"
#endif


Port_ConfigType Port_Pins [NUMBER_OF_PORT_PINS] = {

               PORT_A_PIN_0, PORT_A_ID, PORT_A0_UART0_RX, PORT_PIN_IN, STD_LOW, FALSE, FALSE, FALSE, TRUE,
               PORT_A_PIN_1, PORT_A_ID, PORT_A1_UART0_TX, PORT_PIN_OUT, STD_LOW, FALSE, FALSE, FALSE, TRUE,
               PORT_A_PIN_2, PORT_A_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_A_PIN_3, PORT_A_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, TRUE, FALSE, FALSE, TRUE,
               PORT_A_PIN_4, PORT_A_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_A_PIN_5, PORT_A_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_A_PIN_6, PORT_A_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_A_PIN_7, PORT_A_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,

               PORT_B_PIN_0, PORT_B_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, TRUE, FALSE, TRUE,
               PORT_B_PIN_1, PORT_B_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_B_PIN_2, PORT_B_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_B_PIN_3, PORT_B_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_B_PIN_4, PORT_B_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, TRUE, FALSE, TRUE,
               PORT_B_PIN_5, PORT_B_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_B_PIN_6, PORT_B_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_B_PIN_7, PORT_B_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,

               PORT_C_PIN_0, PORT_C_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_C_PIN_1, PORT_C_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_C_PIN_2, PORT_C_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_C_PIN_3, PORT_C_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_C_PIN_4, PORT_C_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_C_PIN_5, PORT_C_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_C_PIN_6, PORT_C_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_C_PIN_7, PORT_C_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,

               PORT_D_PIN_0, PORT_D_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_D_PIN_1, PORT_D_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_D_PIN_2, PORT_D_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_D_PIN_3, PORT_D_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_D_PIN_4, PORT_D_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_D_PIN_5, PORT_D_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_D_PIN_6, PORT_D_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_D_PIN_7, PORT_D_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,

               PORT_E_PIN_0, PORT_E_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_E_PIN_1, PORT_E_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_E_PIN_2, PORT_E_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_E_PIN_3, PORT_E_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_E_PIN_4, PORT_E_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,
               PORT_E_PIN_5, PORT_E_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, FALSE, TRUE,

               PORT_F_PIN_0, PORT_F_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, TRUE, TRUE,
               PORT_F_PIN_1, PORT_F_ID, PORT_PIN_DIO_MODE, PORT_PIN_OUT, STD_LOW, FALSE, FALSE, FALSE, TRUE,
               PORT_F_PIN_2, PORT_F_ID, PORT_PIN_DIO_MODE, PORT_PIN_OUT, STD_LOW, FALSE, FALSE, FALSE, TRUE,
               PORT_F_PIN_3, PORT_F_ID, PORT_PIN_DIO_MODE, PORT_PIN_OUT, STD_LOW, TRUE, FALSE, FALSE, TRUE,
               PORT_F_PIN_4, PORT_F_ID, PORT_PIN_DIO_MODE, PORT_PIN_IN, STD_HIGH, FALSE, FALSE, TRUE, TRUE,
};


